language: java
sudo: false
dist: xenial
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvoikko1 voikko-fi
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true
